'def saudacao(nome):' 
' return f"Ol , {nome}! Bem-vindo ao software."' 
'if __name__ == "__main__":' 
' nome = input("Digite seu nome: ")' 
' print(saudacao(nome))' 
' if not nome.strip():' 
' nome = "Usu rio"' 
